import { Inter, Oswald, Poppins } from "next/font/google";
import Link from "next/link";
import dynamic from "next/dynamic";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Image from "next/image";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  weight: ["400", "500", "600", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const Scene = dynamic(() => import("@/components/ui/scene"), { ssr: false });

export const metadata = {
  title: "imkpandey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ overscrollBehaviorY: "none" }}
        className={poppins.className}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <div className="flex flex-col min-h-screen">
            <header className="px-4 lg:px-6 h-14 flex items-center z-[99] bg-[#f2f2f2]">
              <Link className="flex items-center justify-center" href="#">
                {/* <Logo className="h-10 w-10" /> */}
                <Image src="/cat.png" width={50} height={50} alt="logo" />
                <span className="sr-only">imkpandey</span>
              </Link>
              <nav className="ml-auto flex gap-4 sm:gap-6">
                <div className="flex justify-center items-center">
                  <Link
                    href="#about"
                    className="nav-link p-4 inline-block relative cursor-pointer"
                  >
                    <span
                      aria-hidden="true"
                      className="relative block overflow-hidden pointer-events-none"
                    >
                      <span className="inline-block transition-all ease-in-out duration-900">
                        About
                        <span className="absolute top-0 left-0 transform translate-y-[200%] text-yellow-500 font-semibold">
                          About
                        </span>
                      </span>
                    </span>
                  </Link>
                  <Link
                    href="#projects"
                    className="nav-link p-4 inline-block relative cursor-pointer"
                  >
                    <span
                      aria-hidden="true"
                      className="relative block overflow-hidden pointer-events-none"
                    >
                      <span className="inline-block transition-all ease-in-out duration-900">
                        Works
                        <span className="absolute top-0 left-0 transform translate-y-[200%] text-yellow-500 font-semibold">
                          Works
                        </span>
                      </span>
                    </span>
                  </Link>
                  <Link
                    href="#contact"
                    className="nav-link p-4 inline-block relative cursor-pointer"
                  >
                    <span
                      aria-hidden="true"
                      className="relative block overflow-hidden pointer-events-none"
                    >
                      <span className="inline-block transition-all ease-in-out duration-900">
                        Contact
                        <span className="absolute top-0 left-0 transform translate-y-[200%] text-yellow-500 font-semibold">
                          Contact
                        </span>
                      </span>
                    </span>
                  </Link>
                </div>
              </nav>
            </header>
            {/* <div className="Mbg fixed top-0 left-0 w-full h-full flex justify-between items-stretch opacity-15 max-h-screen pointer-events-none">
              {Array.from({ length: 12 }, (_, index) => (
                <div
                  key={index}
                  className="Mbg_col w-[1rem] flex-shrink-0 flex justify-between items-stretch"
                >
                  <div className="Mbg_col_el Mbg_col_el-1" />
                  <div className="Mbg_col_el Mbg_col_el-2" />
                </div>
              ))}
            </div> */}
            {children}
          </div>
        </ThemeProvider>
        <Scene />
      </body>
    </html>
  );
}

function Logo(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="172"
      height="171"
      version="1"
      viewBox="0 0 129 128.25"
      {...props}
    >
      <defs>
        <clipPath id="7d4c1eaa80">
          <path d="M.375 0h127.328v127.328H.375Zm0 0"></path>
        </clipPath>
        <clipPath id="b3c645aa46">
          <path d="M64.04 0C28.878 0 .374 28.504.374 63.664s28.504 63.664 63.664 63.664 63.664-28.504 63.664-63.664S99.2 0 64.04 0m0 0"></path>
        </clipPath>
        <clipPath id="def6a8691f">
          <path d="M12.223 11.848h103.632V115.48H12.223Zm0 0"></path>
        </clipPath>
        <clipPath id="e5778a8659">
          <path d="M64.04 11.848c-28.618 0-51.817 23.199-51.817 51.816s23.199 51.816 51.816 51.816 51.816-23.199 51.816-51.816S92.656 11.848 64.04 11.848m0 0"></path>
        </clipPath>
        <clipPath id="932c48ac44">
          <path d="M76.176 63.664h51.816v63.664H76.176Zm0 0"></path>
        </clipPath>
        <clipPath id="7456a667f1">
          <path d="M115.855 57.54h11.848v11.847h-11.848Zm0 0"></path>
        </clipPath>
        <clipPath id="0cc7627505">
          <path d="M121.781 57.54a5.924 5.924 0 1 0-.003 11.847 5.924 5.924 0 0 0 .003-11.848m0 0"></path>
        </clipPath>
        <clipPath id="cca51290c3">
          <path d="M50.61 41.559h55.269v30.496h-55.27Zm0 0"></path>
        </clipPath>
        <clipPath id="e19bde0cdf">
          <path d="M50.61 72.055V41.559l27.636 9.53 27.633-9.53v30.496Zm0 0"></path>
        </clipPath>
        <clipPath id="1fee5686d8">
          <path d="M50.621 44.422h55.27v55.27H50.62Zm0 0"></path>
        </clipPath>
        <clipPath id="74c917963e">
          <path d="M78.254 44.422c-15.262 0-27.633 12.371-27.633 27.637 0 15.261 12.371 27.632 27.633 27.632s27.637-12.37 27.637-27.632c0-15.266-12.375-27.637-27.637-27.637m0 0"></path>
        </clipPath>
        <clipPath id="8e9623e385">
          <path d="M25.422 67.344h55.582v54.722H25.422Zm0 0"></path>
        </clipPath>
        <clipPath id="94e4f847ee">
          <path d="M27.336 85.594c-1.047 2.804-1.734 5.996-1.734 9.125 0 3.133.59 6.144 1.636 8.918.032.058.032.12.063.18 4.183 10.425 15.23 18.101 27.73 18.25h25.973V67.343H55.05c-12.586.144-23.633 7.707-27.715 18.25m0 0"></path>
        </clipPath>
        <clipPath id="bcde899aa1">
          <path d="M64.184 112.922h24.191v14.406H64.184Zm0 0"></path>
        </clipPath>
        <clipPath id="cd2af64a5a">
          <path d="M87.941 122.523a7.6 7.6 0 0 0 .418-2.402c0-.824-.14-1.617-.394-2.348-.008-.015-.008-.03-.016-.046-1.004-2.743-3.656-4.766-6.898-4.805H64.184v14.406h16.855c3.27-.039 5.922-2.031 6.902-4.805m0 0"></path>
        </clipPath>
        <clipPath id="452383d464">
          <path d="M61 66h15v10H61Zm0 0"></path>
        </clipPath>
        <clipPath id="4c2479ff5e">
          <path d="m62.55 65.059 14.454 4.984-2.492 7.227-14.453-4.985Zm0 0"></path>
        </clipPath>
        <clipPath id="efd1484b25">
          <path d="M69.777 67.55c-3.992-1.374-7.785-.874-8.472 1.122-.688 1.996 1.988 4.73 5.98 6.105s7.785.875 8.473-1.12c.687-1.997-1.992-4.731-5.98-6.106m0 0"></path>
        </clipPath>
        <clipPath id="74a42cf62a">
          <path d="M82 66h16v10H82Zm0 0"></path>
        </clipPath>
        <clipPath id="e2a2ac461e">
          <path d="m81.898 69.598 14.696-4.22 2.11 7.349-14.696 4.218Zm0 0"></path>
        </clipPath>
        <clipPath id="a3f203def5">
          <path d="M89.246 67.488c-4.058 1.168-6.875 3.754-6.293 5.785.582 2.028 4.344 2.73 8.402 1.563 4.06-1.164 6.875-3.754 6.293-5.781-.582-2.032-4.343-2.73-8.402-1.567m0 0"></path>
        </clipPath>
      </defs>
      <g clipPath="url(#7d4c1eaa80)">
        <g clipPath="url(#b3c645aa46)">
          <path d="M.375 0h127.328v127.328H.375Zm0 0"></path>
        </g>
      </g>
      <g clipPath="url(#def6a8691f)">
        <g clipPath="url(#e5778a8659)">
          <path
            fill="#fff"
            d="M12.223 11.848h103.632V115.48H12.223Zm0 0"
          ></path>
        </g>
      </g>
      <g clipPath="url(#932c48ac44)">
        <path fill="#fff" d="M76.176 63.664h51.816v63.762H76.176Zm0 0"></path>
      </g>
      <g clipPath="url(#7456a667f1)">
        <g clipPath="url(#0cc7627505)">
          <path d="M115.855 57.54h11.848v11.847h-11.848Zm0 0"></path>
        </g>
      </g>
      <g clipPath="url(#cca51290c3)">
        <g clipPath="url(#e19bde0cdf)">
          <path d="M105.879 72.055h-55.27V41.559h55.27Zm0 0"></path>
        </g>
      </g>
      <g clipPath="url(#1fee5686d8)">
        <g clipPath="url(#74c917963e)">
          <path d="M50.621 44.422h55.27v55.27H50.62Zm0 0"></path>
        </g>
      </g>
      <g clipPath="url(#8e9623e385)">
        <g clipPath="url(#94e4f847ee)">
          <path d="M81.004 67.344v54.722H25.637V67.344Zm0 0"></path>
        </g>
      </g>
      <g clipPath="url(#bcde899aa1)">
        <g clipPath="url(#cd2af64a5a)">
          <path d="M64.184 127.328v-14.406h24.191v14.406Zm0 0"></path>
        </g>
      </g>
      <g clipPath="url(#452383d464)">
        <g clipPath="url(#4c2479ff5e)">
          <g clipPath="url(#efd1484b25)">
            <path
              fill="#ffbd59"
              d="m62.55 65.059 14.454 4.984-2.492 7.227-14.453-4.985Zm0 0"
            ></path>
          </g>
        </g>
      </g>
      <g clipPath="url(#74a42cf62a)">
        <g clipPath="url(#e2a2ac461e)">
          <g clipPath="url(#a3f203def5)">
            <path
              fill="#ffbd59"
              d="m81.898 69.598 14.696-4.22 2.11 7.349-14.696 4.218Zm0 0"
            ></path>
          </g>
        </g>
      </g>
    </svg>
  );
}
