"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/L9jdwEGYcqw
 */
import Link from "next/link";
import dynamic from "next/dynamic";
import Rig from "@/components/canvas/rig";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { Center, Float } from "@react-three/drei";
import Image from "next/image";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/all";
import { useGSAP } from "@gsap/react";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import SplitType from "split-type";
import Typography from "@/components/canvas/typography";

const Common = dynamic(() => import("@/components/canvas/common"), {
  ssr: false,
});

const Blob = dynamic(() => import("@/components/canvas/blob"), {
  ssr: false,
});

const View = dynamic(
  () => import("@react-three/drei").then((mod) => mod.View),
  {
    ssr: false,
    loading: () => (
      <div className="flex h-96 w-full flex-col items-center justify-center">
        <svg
          style={{ width: 40, height: 40 }}
          className="-ml-1 mr-3 h-5 w-5 animate-spin text-black"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            className="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            strokeWidth="4"
          />
          <path
            className="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 0 1 8-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 0 1 4 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          />
        </svg>
      </div>
    ),
  }
);

const projects = [
  {
    name: "MINDPOP",
    description:
      "A creative website made for a creative digital marketing agency",
    link: "https://mindpop.vercel.app",
  },
  {
    name: "MAHADEV DHAM 3D",
    description:
      "A 3D experiment done for a client inspired from hindu mythology",
    link: "https://karauli.vercel.app",
  },
  {
    name: "GODRAY",
    description: "Implementatio of godrays in react-three-fiber",
    link: "https://r3f-godray.vercel.app",
  },
  {
    name: "INFINITY TRAILS",
    description: "infinity trail lights experimentation done in r3f",
    link: "https://r3f-infinity-trails.vercel.app",
  },
  {
    name: "RIPPLE",
    description: "ripple shader implemented in r3f",
    link: "https://r3f-ripple.vercel.app",
  },
  {
    name: "AKIRA LIGHTS",
    description: "r3f tunnel lights inspired from Akira movie",
    link: "https://akira-lights.vercel.app",
  },
  {
    name: "AMONG US ODE",
    description: "An ode to among us crewmates",
    link: "https://amongus-3d.vercel.app",
  },
];

export default function Home() {
  const container = useRef(null);
  const aboutRef = useRef(null);
  const contactRef = useRef(null);

  useLayoutEffect(() => {
    const ctx = gsap.context(() => {
      gsap.registerPlugin(ScrollTrigger);

      const aboutText = new SplitType(".about-copy");
      const aboutChars = aboutText.chars;

      const setOfColumnsOne = gsap.utils.toArray(".set-one");
      const setOfColumnsTwo = gsap.utils.toArray(".set-two");
      const setOfColumnsThree = gsap.utils.toArray(".set-three");
      const contactText = new SplitType(".contact-head");
      const contactWords = contactText.words;

      gsap
        .timeline({
          scrollTrigger: {
            trigger: aboutRef.current,
            start: "top 60%",
            end: "bottom 90%",
            scrub: 1,
          },
        })
        .from(aboutChars, {
          opacity: 0.2,
          stagger: 0.02,
          ease: "power3.out",
        });

      gsap
        .timeline({
          scrollTrigger: {
            trigger: contactRef.current,
            start: "top 30%",
            end: "bottom bottom",
            scrub: 1,
          },
        })
        .from(setOfColumnsOne, {
          yPercent: 20,
          stagger: 0.01,
          ease: "power3.out",
        })
        .from(
          setOfColumnsTwo,
          {
            yPercent: 30,
            stagger: 0.01,
            ease: "power3.out",
          },
          "<"
        )
        .from(
          setOfColumnsThree,
          {
            yPercent: 45,
            stagger: 0.01,
            ease: "power3.out",
          },
          "<"
        )
        .from(
          contactWords,
          {
            yPercent: 100,
            stagger: 0.03,
            ease: "power3.out",
          },
          "-=0.5"
        )
        .from(".black-cat", {
          yPercent: 500,
          ease: "power3.out",
        });

      gsap.to(".black-cat", {
        rotateX: 35,
        duration: 2,
        ease: "power3.out",
        repeat: -1,
        yoyo: true,
      });
    }, container);

    return () => ctx.revert();
  }, []);

  return (
    <main ref={container} className="flex-1">
      <section className="hero flex items-center justify-center w-full h-screen border-y bg-[#f2f2f2]">
        <div className="container w-full">
          <View className="w-full h-screen">
            <Float speed={1} rotationIntensity={2} floatIntensity={1}>
              <Blob scale={2} />
            </Float>
            <Typography />
            <Common controls />
          </View>
        </div>
      </section>
      <section
        id="about"
        ref={aboutRef}
        className="about-section relative flex justify-center items-center w-full h-screen bg-[#101010] text-[#edebe8] overflow-hidden"
      >
        <div className="about-container w-[80%] flex flex-col gap-8">
          <p className="about-text text-lg uppercase tracking-[0.3em]">
            ABOUT ME
          </p>
          <p className="about-copy text-3xl md:text-6xl font-medium">
            Hi, I&apos;m a{" "}
            <span className="text-yellow-500">self-proclaimed</span> creative
            web developer. I create bespoke web experiences by spending half of
            my time coding and other half convincing my code to work.
          </p>
        </div>
      </section>
      <section
        id="projects"
        className="relative flex items-start pb-16 md:pb-36 justify-center w-full min-h-screen bg-[#101010] text-[#edebe8] overflow-hidden"
      >
        <div className="work-list flex flex-col w-full">
          <p className="about-text text-lg px-0 md:px-32 mb-8 uppercase tracking-[0.3em]">
            MY EXPERIMENTS WITH WEB
          </p>
          {projects.map((project, index) => (
            <div
              key={index}
              className="project-item relative w-full h-[110px] border-opacity-30 border-y border-[#edebe8] group"
            >
              <Link
                href={project.link}
                rel="noopener noreferrer"
                target="_blank"
              >
                <div className="project-title absolute px-0 md:px-28 inset-0 flex items-center w-full h-full text-3xl md:text-9xl font-bold uppercase text-[#edebe8] bg-[#101010] group-hover:bg-yellow-500 group-hover:text-[#fff] transition-all duration-500">
                  <span className="inline-block text-center whitespace-nowrap">
                    {project.name}
                  </span>
                </div>
                <div className="project-description absolute inset-0 flex items-center justify-between w-full h-full cursor-pointer">
                  <div className="w-2/3 h-full hidden md:block" />
                  <div className="w-full md:w-1/3 h-full px-0 md:px-28 flex items-center justify-start md:justify-end opacity-0 group-hover:opacity-100 transition-all duration-500 text-sm text-[#bcb3a8] bg-[#101010] group-hover:bg-yellow-500 group-hover:text-[#fff]">
                    {project.description}
                  </div>
                </div>
              </Link>
            </div>
          ))}
        </div>
      </section>
      <section
        id="contact"
        ref={contactRef}
        className="relative flex items-center justify-center w-full h-[200vh] bg-yellow-500 text-[#bcb3a8] overflow-hidden"
      >
        <div className="set-one w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-two w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-three w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-one w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-two w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-one w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-three w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-two w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-one w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-three w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-three w-1/12 h-[200vh] bg-[#101010]" />
        <div className="set-two w-1/12 h-[200vh] bg-[#101010]" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-[200vh] flex flex-col items-center justify-center gap-4">
          <h2 className="contact-head text-[clamp(2.5rem,7vw,7rem)] tracking-tight leading-tight text-center font-black uppercase text-yellow-500 z-[2]">
            <span className="w-fit h-fit overflow-hidden">Not afraid of</span>
            <br />
            <span className="w-fit h-fit overflow-hidden">bothering me</span>
            <br />
            <span className="w-fit h-fit overflow-hidden">
              while I'm watching
            </span>
            <br />
            <span className="w-fit h-fit overflow-hidden">anime?</span>
            <br />
            <span className="text-[clamp(2rem,4vw,4rem)] font-semibold w-[90%] md:w-fit h-fit overflow-hidden text-gray-300">
              <Link href="mailto:imkpandey31@gmail.com">
                Let&apos;s make something big together*
              </Link>
            </span>
          </h2>
          <div className="content w-[360px] h-[100px] z-[2] overflow-hidden">
            <div className="black-cat"></div>
          </div>
          <div className="contact-links mt-4 md:mt-8 flex w-fit h-fit justify-center items-center gap-4 md:gap-8 z-[2]">
            <Link
              className="w-10 h-10"
              href="mailto:imkpandey31@gmail.com"
              rel="noopener noreferrer"
              target="_blank"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="hover:fill-white"
              >
                <path d="M3 3H21C21.5523 3 22 3.44772 22 4V20C22 20.5523 21.5523 21 21 21H3C2.44772 21 2 20.5523 2 20V4C2 3.44772 2.44772 3 3 3ZM20 7.23792L12.0718 14.338L4 7.21594V19H20V7.23792ZM4.51146 5L12.0619 11.662L19.501 5H4.51146Z"></path>
              </svg>
            </Link>
            <Link
              className="w-10 h-10"
              href="https://linkedin.com/in/imkpandey"
              rel="noopener noreferrer"
              target="_blank"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="hover:fill-white"
              >
                <path d="M6.94048 4.99993C6.94011 5.81424 6.44608 6.54702 5.69134 6.85273C4.9366 7.15845 4.07187 6.97605 3.5049 6.39155C2.93793 5.80704 2.78195 4.93715 3.1105 4.19207C3.43906 3.44699 4.18654 2.9755 5.00048 2.99993C6.08155 3.03238 6.94097 3.91837 6.94048 4.99993ZM7.00048 8.47993H3.00048V20.9999H7.00048V8.47993ZM13.3205 8.47993H9.34048V20.9999H13.2805V14.4299C13.2805 10.7699 18.0505 10.4299 18.0505 14.4299V20.9999H22.0005V13.0699C22.0005 6.89993 14.9405 7.12993 13.2805 10.1599L13.3205 8.47993Z"></path>
              </svg>
            </Link>
            <Link
              className="w-10 h-10"
              href="https://github.com/imkpandey"
              rel="noopener noreferrer"
              target="_blank"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="hover:fill-white"
              >
                <path d="M12.001 2C6.47598 2 2.00098 6.475 2.00098 12C2.00098 16.425 4.86348 20.1625 8.83848 21.4875C9.33848 21.575 9.52598 21.275 9.52598 21.0125C9.52598 20.775 9.51348 19.9875 9.51348 19.15C7.00098 19.6125 6.35098 18.5375 6.15098 17.975C6.03848 17.6875 5.55098 16.8 5.12598 16.5625C4.77598 16.375 4.27598 15.9125 5.11348 15.9C5.90098 15.8875 6.46348 16.625 6.65098 16.925C7.55098 18.4375 8.98848 18.0125 9.56348 17.75C9.65098 17.1 9.91348 16.6625 10.201 16.4125C7.97598 16.1625 5.65098 15.3 5.65098 11.475C5.65098 10.3875 6.03848 9.4875 6.67598 8.7875C6.57598 8.5375 6.22598 7.5125 6.77598 6.1375C6.77598 6.1375 7.61348 5.875 9.52598 7.1625C10.326 6.9375 11.176 6.825 12.026 6.825C12.876 6.825 13.726 6.9375 14.526 7.1625C16.4385 5.8625 17.276 6.1375 17.276 6.1375C17.826 7.5125 17.476 8.5375 17.376 8.7875C18.0135 9.4875 18.401 10.375 18.401 11.475C18.401 15.3125 16.0635 16.1625 13.8385 16.4125C14.201 16.725 14.5135 17.325 14.5135 18.2625C14.5135 19.6 14.501 20.675 14.501 21.0125C14.501 21.275 14.6885 21.5875 15.1885 21.4875C19.259 20.1133 21.9999 16.2963 22.001 12C22.001 6.475 17.526 2 12.001 2Z"></path>
              </svg>
            </Link>
          </div>
        </div>
        <div className="footer-text absolute bottom-4 left-1/2 -translate-x-1/2 flex justify-center items-center">
          <p className="text-center text-[clamp(0.75rem,1.25vw,1.25rem)]">
            *That's what she said :/
          </p>
        </div>
      </section>
    </main>
  );
}
